spring.application.name=demo

spring.datasource.url=jdbc:mysql://${DB_HOST}/FinanceAI?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER_M}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ruta interna del contenedor donde se leen los modelos de Data Science
# Si la variable de entorno SHARED_MODELS_PATH no existe (ejecutando en local/IDE),
# usara ../shared-models o ./shared-models
app.shared-models.path=${SHARED_MODELS_PATH:./shared-models}
