spring.application.name=demo

spring.datasource.url=jdbc:mysql://${DB_HOST}/FinanceAI?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER_M}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver

# Ruta interna del contenedor donde se leen los modelos de Data Science
app.shared-models.path=${SHARED_MODELS_PATH:/app/models}